id: P008043
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:57:32.794635
source_metadata:
  id: bdr:W12034
  title: བློ་བཟང་བསྟན་འཛིན་རྒྱ་མཚོའི་རྣམ་ཐར
  author: ''
  volumes:
    408efcd565594ca19433fba3d08006fa:
      image_group_id: I5657
      title: ''
      volume_number: 1
      total_pages: 261
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
