id: P008043
initial_creation_type: ocr
source_metadata:
  id: bdr:W12034
  title: བློ་བཟང་བསྟན་འཛིན་རྒྱ་མཚོའི་རྣམ་ཐར
  author: ''
  volumes:
    408efcd565594ca19433fba3d08006fa:
      image_group_id: I5657
      title: ''
      volume_number: 1
      total_pages: 261
      base_file: v001.txt
ebook_metadata:
  title: བློ་བཟང་བསྟན་འཛིན་རྒྱ་མཚོའི་རྣམ་ཐར
  author: ''
  sku: P008043
  cover: cover.jpg
  layers:
  - pagination
